# -*- coding: utf-8 -*-
"""regression_in_keras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/the-deep-learners/deep-learning-illustrated/blob/master/notebooks/regression_in_keras.ipynb

# Regression Example in Keras
Predicting house prices in Boston, Massachusetts

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/the-deep-learners/deep-learning-illustrated/blob/master/notebooks/regression_in_keras.ipynb)

#### Load dependencies
"""

import numpy as np
from keras.datasets import boston_housing
from keras.models import Sequential
from keras.layers import Dense, Dropout 
from keras.layers.normalization import BatchNormalization

"""#### Load data"""

(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

X_train.shape

X_valid.shape

X_train[0]

y_train[0]

"""#### Design neural network architecture"""

model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

model.summary()

"""#### Configure Model"""

model.compile(loss='mean_squared_error', optimizer='adam')

"""#### Train!"""

model.fit(X_train, y_train, 
          batch_size=8, epochs=32, verbose=1, 
          validation_data=(X_valid, y_valid))

X_valid[42]

y_valid[42]

model.predict(np.reshape(X_valid[42], [1, 13]))

